name: predict_activity
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - joblib
  - pandas
  - scipy
  - rdkit
  - scikit-learn
  - ipykernel
  - cclib
  - freesasa
  - openpyxl
  - jupyterlab
  - seaborn
  - matplotlib
